//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALsSoundSwitcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALsSoundSwitcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring for audio device changes....
        /// </summary>
        internal static string DeviceUtils_Monitor {
            get {
                return ResourceManager.GetString("DeviceUtils_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio device {0} set as default.
        /// </summary>
        internal static string EndpointNotificationCallback_OnDefaultDeviceChanged {
            get {
                return ResourceManager.GetString("EndpointNotificationCallback_OnDefaultDeviceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio device {0} added.
        /// </summary>
        internal static string EndpointNotificationCallback_OnDeviceAdded {
            get {
                return ResourceManager.GetString("EndpointNotificationCallback_OnDeviceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio device {0} removed.
        /// </summary>
        internal static string EndpointNotificationCallback_OnDeviceRemoved {
            get {
                return ResourceManager.GetString("EndpointNotificationCallback_OnDeviceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio device {0} state changed to {1}.
        /// </summary>
        internal static string EndpointNotificationCallback_OnDeviceStateChanged {
            get {
                return ResourceManager.GetString("EndpointNotificationCallback_OnDeviceStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set default device.
        /// </summary>
        internal static string Form1_PerformSwitch_could_not_set_default_device {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_could_not_set_default_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Switching Audio Device.
        /// </summary>
        internal static string Form1_PerformSwitch_Error_Switching_Audio_Device {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_Error_Switching_Audio_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Switching Theme.
        /// </summary>
        internal static string Form1_PerformSwitch_Error_Switching_Theme {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_Error_Switching_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switched Audio Input Device.
        /// </summary>
        internal static string Form1_PerformSwitch_Switched_Audio_Input_Device {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_Switched_Audio_Input_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switched Audio Output Device.
        /// </summary>
        internal static string Form1_PerformSwitch_Switched_Audio_Output_Device {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_Switched_Audio_Output_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading config file .
        /// </summary>
        internal static string Form1_ReadConfig_Error_reading_config_file_ {
            get {
                return ResourceManager.GetString("Form1_ReadConfig_Error_reading_config_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will use default values.
        /// </summary>
        internal static string Form1_ReadConfig_Will_use_default_values {
            get {
                return ResourceManager.GetString("Form1_ReadConfig_Will_use_default_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading device list.
        ///
        ///Could not start .
        /// </summary>
        internal static string Form1_SetupContextMenu_ {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Form1_SetupContextMenu_Edit {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Form1_SetupContextMenu_Exit {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Form1_SetupContextMenu_Help {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Devices.
        /// </summary>
        internal static string Form1_SetupContextMenu_ManageDevices {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_ManageDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Form1_SetupContextMenu_Mode {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string Form1_SetupContextMenu_More {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Form1_SetupContextMenu_Refresh {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Form1_SetupContextMenu_Restart {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Form1_SetupContextMenu_SwitchTheme {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_SwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mixer.
        /// </summary>
        internal static string Form1_SetupContextMenu_VolumeMixer {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_VolumeMixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Installation Required.
        /// </summary>
        internal static string PowerShellUtils_InstallAudioCmdlets_Caption {
            get {
                return ResourceManager.GetString("PowerShellUtils_InstallAudioCmdlets_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To proceed, please allow PowerShell to launch with admin rights..
        /// </summary>
        internal static string PowerShellUtils_InstallAudioCmdlets_Message {
            get {
                return ResourceManager.GetString("PowerShellUtils_InstallAudioCmdlets_Message", resourceCulture);
            }
        }
    }
}
