//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALsSoundSwitcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALsSoundSwitcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Opening Device List File.
        /// </summary>
        internal static string Form1_menuItemEdit_Click_Error_Opening_Device_List_File {
            get {
                return ResourceManager.GetString("Form1_menuItemEdit_Click_Error_Opening_Device_List_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start .
        /// </summary>
        internal static string Form1_menuItemRefresh_Click_Could_not_start_ {
            get {
                return ResourceManager.GetString("Form1_menuItemRefresh_Click_Could_not_start_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Refreshing Device List.
        /// </summary>
        internal static string Form1_menuItemRefresh_Click_Error_Refreshing_Device_List {
            get {
                return ResourceManager.GetString("Form1_menuItemRefresh_Click_Error_Refreshing_Device_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Restarting Application.
        /// </summary>
        internal static string Form1_menuItemRestart_Click_Error_Restarting_Application {
            get {
                return ResourceManager.GetString("Form1_menuItemRestart_Click_Error_Restarting_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try manually closing and starting the application..
        /// </summary>
        internal static string Form1_menuItemRestart_Click_Please_try_manually_closing_and_starting_the_application_ {
            get {
                return ResourceManager.GetString("Form1_menuItemRestart_Click_Please_try_manually_closing_and_starting_the_applicat" +
                        "ion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Switching Audio Device.
        /// </summary>
        internal static string Form1_PerformSwitch_Error_Switching_Audio_Device {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_Error_Switching_Audio_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index (-1?) selected..
        /// </summary>
        internal static string Form1_PerformSwitch_Invalid_index___1___selected_ {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_Invalid_index___1___selected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading config file .
        /// </summary>
        internal static string Form1_ReadConfig_Error_reading_config_file_ {
            get {
                return ResourceManager.GetString("Form1_ReadConfig_Error_reading_config_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will use default values.
        /// </summary>
        internal static string Form1_ReadConfig_Will_use_default_values {
            get {
                return ResourceManager.GetString("Form1_ReadConfig_Will_use_default_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading device list.
        ///
        ///Could not start .
        /// </summary>
        internal static string Form1_SetupContextMenu_ {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string Form1_SetupContextMenu_E_dit {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_E_dit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Form1_SetupContextMenu_Ex_it {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Ex_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Refresh.
        /// </summary>
        internal static string Form1_SetupContextMenu_R_efresh {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_R_efresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re&amp;start.
        /// </summary>
        internal static string Form1_SetupContextMenu_Res_tart {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Res_tart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
