//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALsSoundSwitcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALsSoundSwitcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL&apos;s Sound Switcher.
        /// </summary>
        internal static string ALs_Sound_Switcher {
            get {
                return ResourceManager.GetString("ALs_Sound_Switcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring for audio device changes....
        /// </summary>
        internal static string DeviceUtils_Monitor {
            get {
                return ResourceManager.GetString("DeviceUtils_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio device {0} set as default.
        /// </summary>
        internal static string EndpointNotificationCallback_OnDefaultDeviceChanged {
            get {
                return ResourceManager.GetString("EndpointNotificationCallback_OnDefaultDeviceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio device {0} added.
        /// </summary>
        internal static string EndpointNotificationCallback_OnDeviceAdded {
            get {
                return ResourceManager.GetString("EndpointNotificationCallback_OnDeviceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio device {0} removed.
        /// </summary>
        internal static string EndpointNotificationCallback_OnDeviceRemoved {
            get {
                return ResourceManager.GetString("EndpointNotificationCallback_OnDeviceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio device {0} state changed to {1}.
        /// </summary>
        internal static string EndpointNotificationCallback_OnDeviceStateChanged {
            get {
                return ResourceManager.GetString("EndpointNotificationCallback_OnDeviceStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application config has been modified.
        ///Would you like to restart to apply these changes?.
        /// </summary>
        internal static string FileWatcher_OnChanged {
            get {
                return ResourceManager.GetString("FileWatcher_OnChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A known issue has occurred.
        ///The application will now restart..
        /// </summary>
        internal static string Form1_CacheCurrentDevice_KnownIssue_Restart {
            get {
                return ResourceManager.GetString("Form1_CacheCurrentDevice_KnownIssue_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set default device.
        /// </summary>
        internal static string Form1_PerformSwitch_could_not_set_default_device {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_could_not_set_default_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Switching Audio Device.
        /// </summary>
        internal static string Form1_PerformSwitch_Error_Switching_Audio_Device {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_Error_Switching_Audio_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Switching Theme.
        /// </summary>
        internal static string Form1_PerformSwitch_Error_Switching_Theme {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_Error_Switching_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switched Audio Input Device.
        /// </summary>
        internal static string Form1_PerformSwitch_Switched_Audio_Input_Device {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_Switched_Audio_Input_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switched Audio Output Device.
        /// </summary>
        internal static string Form1_PerformSwitch_Switched_Audio_Output_Device {
            get {
                return ResourceManager.GetString("Form1_PerformSwitch_Switched_Audio_Output_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading config file .
        /// </summary>
        internal static string Form1_ReadConfig_Error_reading_config_file_ {
            get {
                return ResourceManager.GetString("Form1_ReadConfig_Error_reading_config_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will use default values.
        /// </summary>
        internal static string Form1_ReadConfig_Will_use_default_values {
            get {
                return ResourceManager.GetString("Form1_ReadConfig_Will_use_default_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading device list.
        ///
        ///Could not start .
        /// </summary>
        internal static string Form1_SetupContextMenu_ {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string Form1_SetupContextMenu_ControlPanel {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  + New Theme.
        /// </summary>
        internal static string Form1_SetupContextMenu_CreateTheme {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_CreateTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Form1_SetupContextMenu_Edit {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Form1_SetupContextMenu_Exit {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Form1_SetupContextMenu_Help {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch on Startup.
        /// </summary>
        internal static string Form1_SetupContextMenu_LaunchOnStartup {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_LaunchOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Devices.
        /// </summary>
        internal static string Form1_SetupContextMenu_ManageDevices {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_ManageDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Form1_SetupContextMenu_Mode {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string Form1_SetupContextMenu_More {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Form1_SetupContextMenu_MouseControls {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_MouseControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent Auto Switching.
        /// </summary>
        internal static string Form1_SetupContextMenu_PreventAutoSwitch {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_PreventAutoSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Form1_SetupContextMenu_Refresh {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Form1_SetupContextMenu_Restart {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Form1_SetupContextMenu_SwitchTheme {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_SwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Form1_SetupContextMenu_Update {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mixer.
        /// </summary>
        internal static string Form1_SetupContextMenu_VolumeMixer {
            get {
                return ResourceManager.GetString("Form1_SetupContextMenu_VolumeMixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Click.
        /// </summary>
        internal static string Form1_SetupMouseControlsSubmenu_Left_Click {
            get {
                return ResourceManager.GetString("Form1_SetupMouseControlsSubmenu_Left_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Click.
        /// </summary>
        internal static string Form1_SetupMouseControlsSubmenu_Middle_Click {
            get {
                return ResourceManager.GetString("Form1_SetupMouseControlsSubmenu_Middle_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Globals_DeviceModeDictionary_Input {
            get {
                return ResourceManager.GetString("Globals_DeviceModeDictionary_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Globals_DeviceModeDictionary_Output {
            get {
                return ResourceManager.GetString("Globals_DeviceModeDictionary_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Globals_MouseFunctionDictionary_Exit {
            get {
                return ResourceManager.GetString("Globals_MouseFunctionDictionary_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string Globals_MouseFunctionDictionary_Expand {
            get {
                return ResourceManager.GetString("Globals_MouseFunctionDictionary_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Devices.
        /// </summary>
        internal static string Globals_MouseFunctionDictionary_Manage_Devices {
            get {
                return ResourceManager.GetString("Globals_MouseFunctionDictionary_Manage_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🛇.
        /// </summary>
        internal static string Globals_MouseFunctionDictionary_None {
            get {
                return ResourceManager.GetString("Globals_MouseFunctionDictionary_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Globals_MouseFunctionDictionary_Refresh {
            get {
                return ResourceManager.GetString("Globals_MouseFunctionDictionary_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Next Device.
        /// </summary>
        internal static string Globals_MouseFunctionDictionary_Switch_Next_Device {
            get {
                return ResourceManager.GetString("Globals_MouseFunctionDictionary_Switch_Next_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Mode.
        /// </summary>
        internal static string Globals_MouseFunctionDictionary_Toggle_Mode {
            get {
                return ResourceManager.GetString("Globals_MouseFunctionDictionary_Toggle_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mixer.
        /// </summary>
        internal static string Globals_MouseFunctionDictionary_Volume_Mixer {
            get {
                return ResourceManager.GetString("Globals_MouseFunctionDictionary_Volume_Mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Headset {
            get {
                object obj = ResourceManager.GetObject("Headset", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mask_active {
            get {
                object obj = ResourceManager.GetObject("mask_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mask_arrow {
            get {
                object obj = ResourceManager.GetObject("mask_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mask_background {
            get {
                object obj = ResourceManager.GetObject("mask_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mask_border {
            get {
                object obj = ResourceManager.GetObject("mask_border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mask_selected {
            get {
                object obj = ResourceManager.GetObject("mask_selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mask_separator {
            get {
                object obj = ResourceManager.GetObject("mask_separator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mask_text {
            get {
                object obj = ResourceManager.GetObject("mask_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Mic {
            get {
                object obj = ResourceManager.GetObject("Mic", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Input mode to function, allow PowerShell to install the required components. Please try again..
        /// </summary>
        internal static string PowerShellUtils_InstallAudioCmdlets_Error_Message {
            get {
                return ResourceManager.GetString("PowerShellUtils_InstallAudioCmdlets_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Input mode to function, please allow PowerShell to install the required components..
        /// </summary>
        internal static string PowerShellUtils_InstallAudioCmdlets_Message {
            get {
                return ResourceManager.GetString("PowerShellUtils_InstallAudioCmdlets_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory details not found.
        /// </summary>
        internal static string ThemeCreator_Error_Directory {
            get {
                return ResourceManager.GetString("ThemeCreator_Error_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving your theme.
        /// </summary>
        internal static string ThemeCreator_Error_Save {
            get {
                return ResourceManager.GetString("ThemeCreator_Error_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for your theme....
        /// </summary>
        internal static string ThemeCreator_TextBoxDefault {
            get {
                return ResourceManager.GetString("ThemeCreator_TextBoxDefault", resourceCulture);
            }
        }
    }
}
